name       : perl-ipc-system-simple
version    : '1.30'
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/J/JK/JKEENAN/IPC-System-Simple-1.30.tar.gz : 22e6f5222b505ee513058fdca35ab7a1eab80539b98e5ca4a923a70a8ae9ba9e
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Run commands simply, with detailed diagnostics
description: |
    Run commands simply, with detailed diagnostics
builddeps  :
    - perl-test-nowarnings
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
