name       : perl-ipc-system-simple
version    : '1.25'
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/P/PJ/PJF/IPC-System-Simple-1.25.tar.gz : f1b6aa1dfab886e8e4ea825f46a1cbb26038ef3e727fef5d84444aa8035a4d3b
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Run commands simply, with detailed diagnostics
description: |
    Run commands simply, with detailed diagnostics
builddeps  :
    - perl-test-nowarnings
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
